/*
SQLyog Community v12.18 (64 bit)
MySQL - 10.4.8-MariaDB : Database - addiction
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`addiction` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;

USE `addiction`;

/*Table structure for table `code` */

DROP TABLE IF EXISTS `code`;

CREATE TABLE `code` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `Code` varchar(50) NOT NULL,
  `backup_password` varchar(50) CHARACTER SET utf8 NOT NULL,
  `isAdmin` tinyint(1) NOT NULL DEFAULT 0,
  `Created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `type` enum('qr','alphanumeric') NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

/*Data for the table `code` */

insert  into `code`(`Id`,`Code`,`backup_password`,`isAdmin`,`Created_at`,`type`) values 
(1,'12345','11111',0,'2020-05-16 19:49:01','alphanumeric'),
(2,'45678','22222',1,'2020-05-16 19:49:08','alphanumeric'),
(3,'11111','21111',0,'2020-08-12 23:15:46','alphanumeric');

/*Table structure for table `daily_challenge` */

DROP TABLE IF EXISTS `daily_challenge`;

CREATE TABLE `daily_challenge` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `Dispense_Id` int(11) NOT NULL,
  `day1` tinyint(1) DEFAULT NULL,
  `day2` tinyint(1) DEFAULT NULL,
  `day3` tinyint(1) DEFAULT NULL,
  `day4` tinyint(1) DEFAULT NULL,
  `day5` tinyint(1) DEFAULT NULL,
  `day6` tinyint(1) DEFAULT NULL,
  `day7` tinyint(1) DEFAULT NULL,
  `day8` tinyint(1) DEFAULT NULL,
  `day9` tinyint(1) DEFAULT NULL,
  `day10` tinyint(1) DEFAULT NULL,
  `day11` tinyint(1) DEFAULT NULL,
  `day12` tinyint(1) DEFAULT NULL,
  `day13` tinyint(1) DEFAULT NULL,
  `day14` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=70 DEFAULT CHARSET=utf8;

/*Data for the table `daily_challenge` */

insert  into `daily_challenge`(`Id`,`Dispense_Id`,`day1`,`day2`,`day3`,`day4`,`day5`,`day6`,`day7`,`day8`,`day9`,`day10`,`day11`,`day12`,`day13`,`day14`) values 
(27,27,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(28,28,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(29,29,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(30,30,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(31,31,1,1,0,0,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(32,32,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(33,33,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(34,34,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(35,35,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(36,36,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(37,37,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(38,38,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(39,39,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(40,40,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(41,41,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(42,42,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(43,43,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(44,44,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(45,45,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(46,46,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL),
(47,47,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(48,48,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(49,49,NULL,1,NULL,NULL,NULL,1,NULL,NULL,NULL,1,NULL,NULL,1,NULL),
(50,50,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(51,51,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(52,52,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL),
(53,53,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(54,54,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(55,55,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(56,56,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(57,57,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(58,58,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(59,59,1,1,1,0,1,0,NULL,NULL,1,1,NULL,NULL,NULL,NULL),
(60,60,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(61,61,NULL,1,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(62,62,0,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(63,63,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,1,1,NULL),
(64,64,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL),
(65,65,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,1),
(66,66,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1),
(67,67,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(68,68,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1),
(69,69,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

/*Table structure for table `dispense` */

DROP TABLE IF EXISTS `dispense`;

CREATE TABLE `dispense` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `category` varchar(50) NOT NULL,
  `maximumValue` int(5) DEFAULT NULL,
  `hopeValue` int(5) DEFAULT NULL,
  `currentValue` int(5) DEFAULT NULL,
  `deviceId` varchar(100) NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT 1,
  `day_after` int(3) NOT NULL DEFAULT 0,
  `type` varchar(50) NOT NULL,
  `cancel_reason` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `Id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=70 DEFAULT CHARSET=utf8;

/*Data for the table `dispense` */

insert  into `dispense`(`id`,`category`,`maximumValue`,`hopeValue`,`currentValue`,`deviceId`,`created_at`,`updated_at`,`status`,`day_after`,`type`,`cancel_reason`) values 
(63,'Alkohol',NULL,NULL,NULL,'b21d3e92-5edf-4c76-b01d-297ed9b85300','2020-08-10 09:20:37','2020-08-10 09:20:37',0,15,'alkohol','... ich keine Lust mehr habe'),
(64,'Alkohol',NULL,NULL,NULL,'d4ce9547-0213-4c94-bc02-229fc76638b7','2020-08-10 09:23:54','2020-08-10 09:23:54',0,13,'alkohol',NULL),
(65,'Alkohol',NULL,NULL,NULL,'d4ce9547-0213-4c94-bc02-229fc76638b7','2020-08-10 09:55:54','2020-08-10 09:55:54',0,14,'alkohol','... ich keine Lust mehr habe'),
(66,'Alkohol',NULL,NULL,NULL,'d4ce9547-0213-4c94-bc02-229fc76638b7','2020-08-10 09:58:31','2020-08-10 09:58:31',0,15,'alkohol',NULL),
(67,'Alkohol',NULL,NULL,NULL,'aa15ffe1-1549-4429-bd65-a5d6a0d8cc2c','2020-08-10 17:59:50','2020-08-10 17:59:50',0,15,'alkohol',NULL),
(68,'Alkohol',NULL,NULL,NULL,'464f2cf0-f361-46c6-b64d-3c3f5968d2f3','2020-08-10 18:02:18','2020-08-10 18:02:18',0,15,'alkohol',NULL),
(69,'Alkohol',NULL,NULL,NULL,'464f2cf0-f361-46c6-b64d-3c3f5968d2f3','2020-08-12 22:55:25','2020-08-12 22:55:25',0,2,'alkohol',NULL);

/*Table structure for table `reaction` */

DROP TABLE IF EXISTS `reaction`;

CREATE TABLE `reaction` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `dispense_id` int(10) NOT NULL,
  `reaction` int(5) DEFAULT NULL,
  `day1` int(5) DEFAULT NULL,
  `day2` int(5) DEFAULT NULL,
  `day3` int(5) DEFAULT NULL,
  `day4` int(5) DEFAULT NULL,
  `day5` int(5) DEFAULT NULL,
  `day6` int(5) DEFAULT NULL,
  `day7` int(5) DEFAULT NULL,
  `day8` int(5) DEFAULT NULL,
  `day9` int(5) DEFAULT NULL,
  `day10` int(5) DEFAULT NULL,
  `day11` int(5) DEFAULT NULL,
  `day12` int(5) DEFAULT NULL,
  `day13` int(5) DEFAULT NULL,
  `day14` int(5) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=60 DEFAULT CHARSET=utf8mb4;

/*Data for the table `reaction` */

insert  into `reaction`(`id`,`dispense_id`,`reaction`,`day1`,`day2`,`day3`,`day4`,`day5`,`day6`,`day7`,`day8`,`day9`,`day10`,`day11`,`day12`,`day13`,`day14`) values 
(17,27,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(18,28,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(19,29,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(20,30,2,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(21,31,3,3,4,1,5,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(22,32,3,NULL,2,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(23,33,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(24,34,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(25,35,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(26,36,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(27,37,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(28,38,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(29,39,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(30,40,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(31,41,4,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(32,42,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(33,43,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(34,44,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(35,45,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(36,46,2,NULL,NULL,5,NULL,NULL,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,NULL),
(37,47,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(38,48,3,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(39,49,3,NULL,3,NULL,NULL,NULL,2,NULL,NULL,NULL,3,NULL,NULL,3,NULL),
(40,50,3,NULL,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(41,51,2,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(42,52,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,2,NULL),
(43,53,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(44,54,3,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(45,55,NULL,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(46,56,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(47,57,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(48,58,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(49,59,2,3,4,4,3,4,3,NULL,NULL,3,3,NULL,NULL,NULL,NULL),
(50,60,4,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(51,61,3,NULL,2,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(52,62,3,5,NULL,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(53,63,3,NULL,NULL,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,NULL,3,3,NULL),
(54,64,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,4,NULL),
(55,65,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,4,3),
(56,66,4,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,4),
(57,67,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(58,68,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,3),
(59,69,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
